aliases:
  power:
    aliases: 
    - powerexample
    - example
    - power
    - pow
    execute: f p
    requires:
      factionsEnabledInWorld: true
      executerIsPlayer: false
      executerIsInFaction: false
      executerIsLeader: false
    permission: factions.power
    permissionDeniedMessage: 'ยง4You dont have permission to do this!'
    description: 'This is an example!'