name: FactionsAlias
main: com.markehme.factionsalias.FactionsAlias
author: MarkehMe
website: http://markeh.me
version: 1.0.0
depend: [ Factions ]
dev-url: http://dev.bukkit.org/bukkit-plugins/factionsalias/